### ISSUE TITLE
Suggestion: Unlimited Custom Links and Icons for Primary/Secondary Actions

### ISSUE THREAD

**Issue by Leolele99** [vishnuraghavb/EnBizCard#14]
It would be cool to have the option to add additional links/websites in both the primary and secondary action category.

This way, if I have two websites, I can link both. If I have a social media/account that is not yet supported, I can also add it temporarily, for example artstation and buymeacoffee.

Every custom link action could support link, name, and icon fields to allow for seamless integration into the website.

Thank you very much for this awesome project!

**Comment by vishnuraghavb** [comment]
Hi. I can understand that adding custom actions would be cool but at the same time, it could ruin the consistency which EnBizCard currently provides. Because not everyone is gonna spend the time to create/modify the action icons to meet the standards which definitely will make the design look cheap and inconsistent IMO. I hope I was clear enough.
This feature was not enabled only for this reason. Thanks for your interest though! :)

**Comment by vishnuraghavb** [comment]
I've added artstation and buymeacoffee under secondary actions now :)
